### ISSUE TITLE
[Update Request] Add Instruction to using sast and update readme more readable

### ISSUE THREAD

**Issue by kukuhsw** [ksatriow/sast#5]
## Description

Firstly, I would like to express my gratitude for developing and sharing this project. It's a fantastic tool that I believe many will find incredibly useful. However, I noticed that the current README does not include any information on how to install the tools provided by the project.

## Suggestion
Could you please update the README to include detailed installation instructions? This will greatly help new users to set up the tool quickly and efficiently.

**Comment by ksatriow** [comment]
Already update the readme, @kukuhsw please check newest readme [README](https://github.com/ksatriow/sast/blob/main/README.md)
